name: Enviar métricas para 4TechLead

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  checks: read
  statuses: read

jobs:
  send-pr-metrics:
    uses: ronannc/4TechLead---backend/.github/workflows/for-tech-lead-central.yml@main
    with:
      actor_map: ${{ vars.FOR_TECH_LEAD_ACTOR_MAP }}
    secrets:
      FOR_TECH_LEAD_TOKEN: ${{ secrets.FOR_TECH_LEAD_TOKEN }}
